### ISSUE TITLE
Jekyll config file creator

### ISSUE THREAD

**Issue by sergiokopplin** [sergiokopplin/ideas#1]
A simple tool that creates a jekyll config file with a simple form

**Comment by renatogalvones** [comment]
Suggestion: What if you make a form and in the end(it doesn't even matt... ok stop it!) you give the content of the _config instead of creating the file itself?

Something like: "here your config file! replace the content of _config.yml file with this data. Click here to copy to clipboard. "

**Comment by sergiokopplin** [comment]
I started doing, but i didn't like the first results, so i'm closing this down!
